/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AdjustmentCount = number;
export type BankCredit = number | null;
export type BankDate = string | null;
export type BankNarration = string | null;
export type BankRef = string | null;
export type Amount = number;
export type Attributed = boolean;
export type Check = string;
export type Confidence = number | null;
export type Detail = string;
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "ComponentKind".
 */
export type ComponentKind =
  "fee" | "gst_on_fee" | "fee_rate_drift" | "cross_cycle_refund" | "unlinked_adjustment" | "rounding" | "unexplained";
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "ComponentSource".
 */
export type ComponentSource = "deterministic" | "llm";
export type Components = GapComponent[];
export type Explained = number;
export type GrossSettled = number;
export type HeadlineGap = number;
export type BankRef1 = string | null;
export type Basis = string;
export type CandidatesConsidered = number;
export type Confidence1 = number;
export type MatchOrigin = "deterministic" | "inference" | "none";
export type RejectedReason = string | null;
export type MatchRule = "R1" | "R2" | "R3" | "R4" | "none";
export type OrdersExpected = number;
export type PaymentCount = number;
export type RefundCount = number;
export type Residual = number;
export type RowCount = number;
export type SettledAt = string;
export type SettlementExpectedCredit = number;
export type SettlementId = string;
export type SettlementResidual = number;
export type TotalFee = number;
export type TotalTax = number;
export type Action = string;
export type Detail1 = string;
export type Stage = string;
export type Trace = TraceEntry[];
export type Utr = string;
export type WindowEnd = string;
export type WindowStart = string;
export type Batches = BatchReport[];
export type ReportedAmount = number;
export type TruthAmount = number;
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "Verdict".
 */
export type Verdict = "correct" | "missed" | "over_attributed" | "false_cause";
export type Components1 = EvalComponent[];
export type Passed = boolean;
export type ReportedGap = number;
export type SettlementId1 = string;
export type TruthGap = number;
export type Batches1 = EvalBatch[];
export type Actual = string;
export type Expected = string;
export type Name = string;
export type Number = number;
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "CaseStatus".
 */
export type CaseStatus = "pass" | "fail" | "pending";
export type Cases = EvalCase[];
export type CasesFailed = number;
export type CasesPassed = number;
export type CasesPending = number;
export type CasesTotal = number;
export type FalseCauseAttributions = number;
export type FalseMatches = number;
export type GapAccuracyPct = number;
export type Amount1 = number;
export type BankRef2 = string | null;
export type Candidates = string[];
export type Confidence2 = number | null;
export type Id = string;
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "ExceptionKind".
 */
export type ExceptionKind =
  "ambiguous_match" | "duplicate_utr" | "unmatched_bank_credit" | "unmatched_settlement" | "unexplained_residue";
export type Needs = string;
export type Check1 = string;
export type Reason = string;
export type RuledOut = RuledOut1[];
export type SettlementId2 = string | null;
export type Threshold = number | null;
export type Attributed1 = number | null;
export type Check2 = string;
export type Outcome = string;
export type Tried = Attempt[];
export type What = string;
export type Exceptions = ExceptionReport[];
export type DataDir = string;
export type DeterministicHash = string;
export type LlmCacheHits = number;
export type LlmCalls = number;
export type LlmErrorDetail = string;
export type LlmErrors = number;
export type LlmMode = "stub" | "cache" | "live" | "off";
export type LlmProvider = string;
export type RunAt = string | null;
export type RuntimeMs = number;
export type SchemaVersion = string;
export type Seed = number;
export type Confidence3 = number;
export type Counterparty = string | null;
export type Kind = string;
export type MatchedSettlementId = string | null;
export type Notes = string[];
export type Raw = string;
export type Ref = string;
export type Source = string;
export type Utrs = string[];
export type Narrations = NarrationRead[];
export type Canonical = string;
export type Confidence4 = number;
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "MappingMethod".
 */
export type MappingMethod = "exact" | "alias" | "llm";
export type Source1 = string;
export type ColumnsMapped = ColumnMapping[];
export type File = string;
export type Rejections = string[];
export type RowsRead = number;
export type RowsRejected = number;
export type Normalise = NormaliseReport[];
export type BankRows = number;
export type FalseCauseAttributions1 = number;
export type FalseMatches1 = number;
export type GapExplained = number;
export type GapExplainedPct = number;
export type GapTotal = number;
export type GapUnexplained = number;
export type GapUnexplainedPct = number;
export type N = number;
export type Pct = number;
export type OrderRows = number;
export type RecordsProcessed = number;
export type RuntimeMs1 = number;
export type SettlementBatches = number;
export type SettlementRows = number;
export type Credit = number;
export type Date = string;
export type Narration = string;
export type Reason1 = string;
export type Ref1 = string;
export type UnmatchedBankRows = UnmatchedBankRow[];
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "LlmMode".
 */
export type LlmMode1 = "stub" | "cache" | "live" | "off";
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "MatchOrigin".
 */
export type MatchOrigin1 = "deterministic" | "inference" | "none";
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "MatchRule".
 */
export type MatchRule1 = "R1" | "R2" | "R3" | "R4" | "none";

export interface Report {
  batches: Batches;
  evaluation: EvalReport | null;
  exceptions: Exceptions;
  meta: RunMeta;
  narrations: Narrations;
  normalise: Normalise;
  scoreboard: Scoreboard;
  unmatched_bank_rows: UnmatchedBankRows;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "BatchReport".
 */
export interface BatchReport {
  adjustment_count: AdjustmentCount;
  bank_credit: BankCredit;
  bank_date: BankDate;
  bank_narration: BankNarration;
  bank_ref: BankRef;
  components: Components;
  explained: Explained;
  gross_settled: GrossSettled;
  headline_gap: HeadlineGap;
  match: Match;
  orders_expected: OrdersExpected;
  payment_count: PaymentCount;
  refund_count: RefundCount;
  residual: Residual;
  row_count: RowCount;
  settled_at: SettledAt;
  settlement_expected_credit: SettlementExpectedCredit;
  settlement_id: SettlementId;
  settlement_residual: SettlementResidual;
  total_fee: TotalFee;
  total_tax: TotalTax;
  trace: Trace;
  utr: Utr;
  window_end: WindowEnd;
  window_start: WindowStart;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "GapComponent".
 */
export interface GapComponent {
  amount: Amount;
  attributed: Attributed;
  check: Check;
  confidence: Confidence;
  detail: Detail;
  kind: ComponentKind;
  source: ComponentSource;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "Match".
 */
export interface Match {
  bank_ref: BankRef1;
  basis: Basis;
  candidates_considered: CandidatesConsidered;
  confidence: Confidence1;
  origin: MatchOrigin;
  rejected_reason: RejectedReason;
  rule: MatchRule;
}
/**
 * One recorded step. Every conclusion traces back to one of these.
 *
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "TraceEntry".
 */
export interface TraceEntry {
  action: Action;
  detail: Detail1;
  stage: Stage;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "EvalReport".
 */
export interface EvalReport {
  batches: Batches1;
  cases: Cases;
  cases_failed: CasesFailed;
  cases_passed: CasesPassed;
  cases_pending: CasesPending;
  cases_total: CasesTotal;
  false_cause_attributions: FalseCauseAttributions;
  false_matches: FalseMatches;
  gap_accuracy_pct: GapAccuracyPct;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "EvalBatch".
 */
export interface EvalBatch {
  components: Components1;
  passed: Passed;
  reported_gap: ReportedGap;
  settlement_id: SettlementId1;
  truth_gap: TruthGap;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "EvalComponent".
 */
export interface EvalComponent {
  kind: ComponentKind;
  reported_amount: ReportedAmount;
  truth_amount: TruthAmount;
  verdict: Verdict;
}
/**
 * One of the planted cases from the PRD's table, scored explicitly.
 *
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "EvalCase".
 */
export interface EvalCase {
  actual: Actual;
  expected: Expected;
  name: Name;
  number: Number;
  status: CaseStatus;
}
/**
 * An honest exception, built to be actionable rather than a dump.
 *
 * ``tried`` and ``ruled_out`` are what separate "we could not explain this" from
 * "we did not look". A finance team can act on the first and cannot act on the
 * second.
 *
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "ExceptionReport".
 */
export interface ExceptionReport {
  amount: Amount1;
  bank_ref: BankRef2;
  candidates: Candidates;
  confidence: Confidence2;
  id: Id;
  kind: ExceptionKind;
  needs: Needs;
  ruled_out: RuledOut;
  settlement_id: SettlementId2;
  threshold: Threshold;
  tried: Tried;
  what: What;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "RuledOut".
 */
export interface RuledOut1 {
  check: Check1;
  reason: Reason;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "Attempt".
 */
export interface Attempt {
  attributed: Attributed1;
  check: Check2;
  outcome: Outcome;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "RunMeta".
 */
export interface RunMeta {
  data_dir: DataDir;
  deterministic_hash: DeterministicHash;
  llm_cache_hits: LlmCacheHits;
  llm_calls: LlmCalls;
  llm_error_detail: LlmErrorDetail;
  llm_errors: LlmErrors;
  llm_mode: LlmMode;
  llm_provider: LlmProvider;
  run_at: RunAt;
  runtime_ms: RuntimeMs;
  schema_version: SchemaVersion;
  seed: Seed;
}
/**
 * What was read off one bank line, and by what.
 *
 * ``source`` is the point of this record: it distinguishes what a regular expression
 * could see from what a model was needed for, which is how the AI's contribution
 * stops being a claim and becomes a number.
 *
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "NarrationRead".
 */
export interface NarrationRead {
  confidence: Confidence3;
  counterparty: Counterparty;
  kind: Kind;
  matched_settlement_id: MatchedSettlementId;
  notes: Notes;
  raw: Raw;
  ref: Ref;
  source: Source;
  utrs: Utrs;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "NormaliseReport".
 */
export interface NormaliseReport {
  columns_mapped: ColumnsMapped;
  file: File;
  rejections: Rejections;
  rows_read: RowsRead;
  rows_rejected: RowsRejected;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "ColumnMapping".
 */
export interface ColumnMapping {
  canonical: Canonical;
  confidence: Confidence4;
  method: MappingMethod;
  source: Source1;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "Scoreboard".
 */
export interface Scoreboard {
  bank_rows: BankRows;
  false_cause_attributions: FalseCauseAttributions1;
  false_matches: FalseMatches1;
  gap_explained: GapExplained;
  gap_explained_pct: GapExplainedPct;
  gap_total: GapTotal;
  gap_unexplained: GapUnexplained;
  gap_unexplained_pct: GapUnexplainedPct;
  matched_deterministic: Count;
  matched_inference: Count;
  order_rows: OrderRows;
  records_processed: RecordsProcessed;
  runtime_ms: RuntimeMs1;
  settlement_batches: SettlementBatches;
  settlement_rows: SettlementRows;
  unmatched: Count;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "Count".
 */
export interface Count {
  n: N;
  pct: Pct;
}
/**
 * This interface was referenced by `Report`'s JSON-Schema
 * via the `definition` "UnmatchedBankRow".
 */
export interface UnmatchedBankRow {
  credit: Credit;
  date: Date;
  narration: Narration;
  reason: Reason1;
  ref: Ref1;
}
